version: '3.7'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_REGION_NAME: us-east-1
      MINIO_REGION: us-east-1
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - minio-data:/data
    networks:
      paimon-network:
        ipv4_address: 172.20.0.12

  mc-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      mc alias set myminio http://minio:9000 minio minio123 &&
      mc mb myminio/datalake || true
      "
    networks:
      - paimon-network

  jobmanager:
    image: flink:1.20.0
    container_name: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - HADOOP_CLASSPATH='hadoop classpath'
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - S3_ENDPOINT=http://minio:9000
      - S3_PATH_STYLE_ACCESS=true
    extra_hosts:
      - "hive-metastore:172.20.0.5"
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./jars/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ./jars/flink-s3-fs-hadoop-1.20.0.jar:/opt/flink/plugins/s3-fs-hadoop/flink-s3-fs-hadoop-1.20.0.jar
      - ./jars/paimon-flink-1.20-0.9.0.jar:/opt/flink/lib/paimon-flink-1.20-0.9.0.jar
      - ./jars/paimon-s3-0.9.0.jar:/opt/flink/lib/paimon-s3-0.9.0.jar
      - ./jars/flink-sql-connector-hive-3.1.3_2.12-1.20.0.jar:/opt/flink/lib/flink-sql-connector-hive-3.1.3_2.12-1.20.0.jar
      - ./hive-site.xml:/opt/flink/conf/hive-site.xml
    deploy:
          replicas: 1
    networks:
      paimon-network:
        ipv4_address: 172.20.2.1
  

  taskmanager:
    image: flink:1.20.0
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - HADOOP_CLASSPATH='hadoop classpath'
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - S3_ENDPOINT=http://minio:9000
      - S3_PATH_STYLE_ACCESS=true
    extra_hosts:
      - "hive-metastore:172.20.0.5"
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./jars/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar:/opt/flink/lib/flink-shaded-hadoop-2-uber-2.8.3-10.0.jar
      - ./jars/flink-s3-fs-hadoop-1.20.0.jar:/opt/flink/plugins/s3-fs-hadoop/flink-s3-fs-hadoop-1.20.0.jar
      - ./jars/paimon-flink-1.20-0.9.0.jar:/opt/flink/lib/paimon-flink-1.20-0.9.0.jar
      - ./jars/paimon-s3-0.9.0.jar:/opt/flink/lib/paimon-s3-0.9.0.jar
      - ./jars/flink-sql-connector-hive-3.1.3_2.12-1.20.0.jar:/opt/flink/lib/flink-sql-connector-hive-3.1.3_2.12-1.20.0.jar
      - ./hive-site.xml:/opt/flink/conf/hive-site.xml
    deploy:
          replicas: 6
    networks:
      - paimon-network

  metastore_db:
    image: postgres:11
    hostname: metastore_db
    container_name: metastore_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    networks:
      paimon-network:
        ipv4_address: 172.20.1.1

  hive-metastore:
    container_name: hive-metastore
    hostname: hive-metastore
    image: 'starburstdata/hive:3.1.3-e.12'
    ports:
      - '9083:9083'
    environment:
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://metastore_db:5432/metastore
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3://datalake/
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_PATH_STYLE_ACCESS: "true"
      REGION: ""
      GOOGLE_CLOUD_KEY_FILE_PATH: ""
      AZURE_ADL_CLIENT_ID: ""
      AZURE_ADL_CREDENTIAL: ""
      AZURE_ADL_REFRESH_URL: ""
      AZURE_ABFS_STORAGE_ACCOUNT: ""
      AZURE_ABFS_ACCESS_KEY: ""
      AZURE_WASB_STORAGE_ACCOUNT: ""
      AZURE_ABFS_OAUTH: ""
      AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ""
      AZURE_ABFS_OAUTH_CLIENT_ID: ""
      AZURE_ABFS_OAUTH_SECRET: ""
      AZURE_ABFS_OAUTH_ENDPOINT: ""
      AZURE_WASB_ACCESS_KEY: ""
      HIVE_METASTORE_USER_IN_ADMIN_ROLE: "admin"
    depends_on:
      - metastore_db
    networks:
      paimon-network:
        ipv4_address: 172.20.0.5

  doris-fe:
    image: apache/doris:doris-fe-2.1.7
    hostname: doris-fe
    environment:
      - FE_SERVERS=fe1:172.20.0.14:9010
      - FE_ID=1
      - PRIORITY_NETWORKS=172.20.0.0/16
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - AWS_REGION=us-east-1
      - S3_ENDPOINT=http://minio:9000
    volumes:
      - doris-fe-meta:/opt/apache-doris/fe/doris-meta/
      - doris-fe-log:/opt/apache-doris/fe/log/
      - ./doris-plugins/fe-plugins:/opt/apache-doris/fe/plugins
      - ./fe.conf:/opt/apache-doris/fe/conf/fe.conf
    ports:
      - "18030:8030"
      - "19020:9020"
      - "19030:9030"
      - "19010:9010"
    networks:
      paimon-network:
        ipv4_address: 172.20.0.14
    extra_hosts:
      - "hive-metastore:172.20.0.5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.20.0.14:8030"]
      interval: 30s
      timeout: 10s
      retries: 3

  doris-be:
    image: apache/doris:doris-be-2.1.7
    hostname: doris-be
    environment:
      - FE_SERVERS=fe1:172.20.0.14:9010
      - BE_ADDR=172.20.0.15:9050
      - PRIORITY_NETWORKS=172.20.0.0/16
    volumes:
      - doris-be-storage:/opt/apache-doris/be/storage/
      - doris-be-script:/docker-entrypoint-initdb.d/
    ports:
      - "19050:9050"
      - "19060:9060"
      - "19070:9070"
    ulimits:
      nofile:
        soft: 655350
        hard: 655350
    networks:
      paimon-network:
        ipv4_address: 172.20.0.15

volumes:
  minio-data:
  doris-fe-meta:
  doris-fe-log:
  doris-be-storage:
  doris-be-script:

networks:
  paimon-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16